version: '3'

services:

  web:
    container_name: web
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/workspace
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/workspace
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/script:/docker-entrypoint-initdb.d

volumes:
  postgres-data: