name: auto-merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

permissions:
  pull-requests: write
  contents: write

jobs:
  toggle-auto-merge:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable auto-merge for Steward PRs
        if: ${{ (contains(github.event.pull_request.labels.*.name, 'auto-merge')) }}
        run: gh pr merge --auto "$PR_URL"
      - name: Disable auto-merge for Steward PRs
        if: ${{ !(contains(github.event.pull_request.labels.*.name, 'auto-merge')) }}
        run: gh pr merge --disable-auto "$PR_URL"