name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *'
  workflow_dispatch:

jobs:

  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN}}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: 'kokiwaku/test-renovate-template'
          RENOVATE_USERNAME: 'renovate[bot]'
          RENOVATE_PLATFORM: 'github'