name: status-check

on:
  workflow_dispatch:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      # see https://github.com/reviewdog/action-eslint
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: './src/'
          eslint_flags: 'resources/**/*.{js,ts}'
          fail_on_error: true

  # needsに指定したjobが一つでも失敗した場合、exit 1（失敗する）
  status-check:
    runs-on: ubuntu-latest
    needs:
      - eslint
    if: failure()
    steps:
      - run: exit 1
