name: status-check

on:
  workflow_dispatch:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      # see https://github.com/reviewdog/action-eslint
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: './src/'
          eslint_flags: 'resources/**/*.{js,ts}'
          fail_on_error: true

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: |
          cd src
          composer install
      - name: Run PHP CS Fixer
        run: |
          cd src
          composer run cs-fixer-dry-run

  status-check:
    runs-on: ubuntu-latest
    needs:
      - eslint
      - php-cs-fixer
    permissions:
      pull-requests: write
      contents: write
    steps:
      # status-checkに成功した場合には、PRをapproveする
      - name: Approve PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()
        run: gh pr review "$PR_URL" --approve
      # 失敗した場合には、終了
      - name: Failure
        if: failure()
        run: exit 1
